### ISSUE TITLE
Notícia Nova

### ISSUE THREAD

**Issue by lipito** [n1z/vpl.pt#6]
Colocar nova notícia:
 

> Catálogo de 2017 – IMPULSIONE O SEU NEGÓCIO
>  
> A VPL, representante exclusivo da DSE – Danish  Sign Export, apresenta o novo catálogo com 32 novos produtos e uma nova organização muito mais user friendly.
>  
> Das novidades que agora apresentamos destacamos os novos stands modelares, vitrines e o expositores de chão com luz.
>  
> A DSE  está entre os lideres Europeus no fornecimento de expositores profissionais para feiras e eventos, bem como sinalética de rua, equipamento e paredes para janelas de loja, entre muitos outros produtos.
>  
> Consulte o nosso site ou solicite uma reunião (link para Contactos) para lhe apresentarmos o catálogo em papel.
>  
> A VPL garante qualidade, prazos de entrega rigorosos e apoio pós-venda.
>  
> Consulte já o novo catálogo, aqui! 
> ` adicionar o link do catálogo`

**Comment by joaaoleite** [comment]
"retirar a menção _Comments are closed_ no interior das notícias" movido para novo issue
